# Generated by tools/contracts/gen_models.py from contracts/openapi/prp-client.yaml (ADR-PRP-013).
# DO NOT EDIT. Change the YAML, then run: python tools/contracts/gen_models.py
# generated by datamodel-codegen:
#   filename:  prp-client.yaml

from __future__ import annotations

from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    ConfigDict,
    Field,
    RootModel,
    StrictBool,
    StrictFloat,
    StrictInt,
)

from prp.contracts.base import ContractModel


class ErrorBody(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str
    type: str
    message: str
    param: str | None = None


class Model(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    object: Literal["model"]
    created: StrictInt | None = None
    owned_by: str | None = None


class ModelList(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    object: Literal["list"]
    data: list[Model]


class CapabilityLimits(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_context_tokens: StrictInt | None = None
    max_audio_seconds: StrictFloat | None = None
    max_input_bytes: StrictInt | None = None
    max_tts_codepoints: StrictInt | None = None


class ToolFunction(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(max_length=64)]
    description: str | None = None
    parameters: dict[str, Any] | None = None
    strict: StrictBool | None = None


class FunctionCall(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    arguments: str


class FunctionName(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str


class Usage(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    prompt_tokens: Annotated[StrictInt, Field(ge=0)]
    completion_tokens: Annotated[StrictInt, Field(ge=0)]
    total_tokens: Annotated[StrictInt, Field(ge=0)]


class Segment(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: Annotated[StrictFloat, Field(ge=0.0)]
    end: Annotated[StrictFloat, Field(ge=0.0)]
    text: str


class Transcript(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str
    language: str
    duration_seconds: Annotated[StrictFloat, Field(ge=0.0)]
    segments: list[Segment] | None = None
    profile_revision: str


class SpeechRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model: str
    input: Annotated[str, Field(max_length=800, min_length=1)]
    voice: str
    response_format: Literal["wav", "mp3"]
    speed: Annotated[StrictFloat, Field(ge=0.5, le=2.0)] = 1


class Artifact(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: UUID
    mime_type: str
    duration_seconds: Annotated[StrictFloat, Field(ge=0.0)]
    checksum_sha256: Annotated[str | None, Field(pattern="^[a-f0-9]{64}$")] = None
    expires_at: AwareDatetime


class AsrJobRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["asr"]
    model: str
    input_artifact_id: UUID
    language: Literal["th", "en", "auto"] | None = None
    deadline_seconds: Annotated[StrictInt, Field(ge=1, le=180)] = 180
    external_reference: Annotated[str | None, Field(max_length=128)] = None


class TtsJobRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["tts"]
    model: str
    input: Annotated[str, Field(max_length=800, min_length=1)]
    voice: str
    response_format: Literal["wav", "mp3"]
    deadline_seconds: Annotated[StrictInt, Field(ge=1, le=180)] = 180
    external_reference: Annotated[str | None, Field(max_length=128)] = None


class JobRequest(RootModel[AsrJobRequest | TtsJobRequest]):
    root: Annotated[AsrJobRequest | TtsJobRequest, Field(discriminator="kind")]


class TtsJobResult(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    artifact_id: UUID


class GrantRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ttl_seconds: Annotated[StrictInt, Field(ge=60, le=86400)]


class Grant(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    grant_id: UUID
    url: AnyUrl
    expires_at: AwareDatetime


class Error(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: ErrorBody
    request_id: str
    safe_to_retry: StrictBool


class Capability(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model: str
    profile_revision: str
    capabilities: list[Literal["chat", "asr", "tts", "tool_calls"]]
    languages: list[str] | None = None
    formats: list[str] | None = None
    limits: CapabilityLimits | None = None
    status: Literal["ready", "unavailable"]


class Tool(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["function"]
    function: ToolFunction


class ToolCall(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    type: Literal["function"]
    function: FunctionCall


class Message(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Literal["system", "user", "assistant", "tool"]
    content: str | None
    tool_call_id: str | None = None
    tool_calls: list[ToolCall] | None = None


class NamedToolChoice(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["function"]
    function: FunctionName


class ChatChoice(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    index: StrictInt
    message: Message
    finish_reason: Literal["stop", "length", "tool_calls"]


class Job(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    job_id: UUID
    request_id: str
    kind: Literal["asr", "tts"]
    outcome: Literal["PENDING", "SUCCEEDED", "FAILED", "TIMED_OUT", "CANCELLED"]
    execution_status: Literal["QUEUED", "RESERVED", "DISPATCHED", "RUNNING", "UNKNOWN", "FINISHED"]
    cancellation_requested: StrictBool
    status_path: str
    created_at: AwareDatetime
    deadline_at: AwareDatetime
    result: Transcript | TtsJobResult | None = None
    error: Error | None = None
    usage_provenance: Literal["actual", "estimated", "unavailable"] | None = None


class JobList(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data: list[Job]
    next_cursor: str | None


class ChatRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model: str
    messages: Annotated[list[Message], Field(min_length=1)]
    stream: StrictBool = False
    temperature: Annotated[StrictFloat | None, Field(ge=0.0, le=2.0)] = None
    top_p: Annotated[StrictFloat | None, Field(gt=0.0, le=1.0)] = None
    max_tokens: Annotated[StrictInt | None, Field(ge=1, le=8192)] = None
    tools: list[Tool] | None = None
    tool_choice: Literal["auto", "none", "required"] | NamedToolChoice | None = None
    n: Literal[1] | None = None


class ChatResponse(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    object: Literal["chat.completion"]
    created: StrictInt
    model: str
    choices: list[ChatChoice]
    usage: Usage | None = None
