# Generated by tools/contracts/gen_models.py from contracts/openapi/prp-management.yaml (ADR-PRP-013).
# DO NOT EDIT. Change the YAML, then run: python tools/contracts/gen_models.py
# generated by datamodel-codegen:
#   filename:  prp-management.yaml

from __future__ import annotations

from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    ConfigDict,
    Field,
    RootModel,
    StrictBool,
    StrictInt,
)

from prp.contracts.base import ContractModel


class ErrorBody(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Literal[
        "INVALID_REQUEST",
        "UNSUPPORTED_PARAMETER",
        "INVALID_KEY",
        "EXPIRED_KEY",
        "SCOPE_DENIED",
        "POLICY_DENIED",
        "NOT_FOUND",
        "IDEMPOTENCY_CONFLICT",
        "VERSION_CONFLICT",
        "QUALIFICATION_REQUIRED",
        "STATE_STORE_UNAVAILABLE",
    ]
    type: str
    message: str
    param: str | None = None


class MutationReceipt(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource_id: str
    version: Annotated[
        str,
        Field(description="New resource version to send as If-Match on the next mutation"),
    ]
    audit_event_id: UUID
    request_id: str


class AccessGrantRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_type: Literal["organization", "principal", "application"]
    subject_id: str
    pool_id: UUID
    scopes: Annotated[list[str], Field(min_length=1)]
    expires_at: AwareDatetime | None = None


class KeyRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_type: Literal["principal", "application"]
    subject_id: str
    scopes: Annotated[list[str], Field(min_length=1)]
    pool_ids: Annotated[list[UUID], Field(min_length=1)]
    expires_at: AwareDatetime | None = None
    label: Annotated[str | None, Field(max_length=128)] = None


class KeyIssued(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key_id: UUID
    secret: Annotated[
        str,
        Field(
            description="Shown once; never retrievable, exportable or restorable afterwards (PRP-FR-005)"
        ),
    ]
    key_prefix: Annotated[
        str, Field(description="Non-secret prefix for identification in logs and UI")
    ]
    scopes: list[str]
    expires_at: AwareDatetime | None = None
    version: str
    audit_event_id: UUID
    request_id: str


class PoolRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(max_length=64, min_length=1)]
    description: Annotated[str | None, Field(max_length=512)] = None


class NodeRegistration(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pool_id: UUID
    origin: Annotated[
        AnyUrl,
        Field(description="Allowed worker/adapter endpoint on the private network"),
    ]
    physical_resource_id: Annotated[
        str,
        Field(
            description="host + GPU UUID, verified host-local identity or CPU pool (ARCH-PRP §5)"
        ),
    ]
    runtime_uid: str
    credential_ref: Annotated[
        str,
        Field(
            description="Reference to the service credential in the secret store; never the credential itself"
        ),
    ]
    desired_profile_id: str


class NodeUpdate(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    origin: AnyUrl | None = None
    credential_ref: str | None = None
    desired_profile_id: str | None = None
    max_concurrent_invocations: Annotated[StrictInt | None, Field(ge=1)] = None


class AcceptanceTestId(RootModel[str]):
    root: Annotated[str, Field(pattern="^PRP-AT-[0-9]{3}$")]


class StateChangeRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reason: Annotated[str | None, Field(max_length=512)] = None


class ProfileApproval(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["model", "voice"]
    revision: str
    license_receipt_ref: Annotated[
        str,
        Field(
            description="Reference to the recorded license / voice-rights receipt; not the document itself"
        ),
    ]
    approved_until: AwareDatetime | None = None


class PolicyScope(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    organization_id: str | None = None
    application_id: str | None = None


class ExportRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["usage", "audit"]
    from_: Annotated[AwareDatetime, Field(alias="from")]
    to: AwareDatetime
    organization_id: str | None = None


class ExportJob(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    export_id: UUID
    kind: Literal["usage", "audit"]
    status: Literal["PENDING", "READY", "FAILED"]
    redaction: Literal["redacted"]
    artifact_id: UUID | None = None
    expires_at: AwareDatetime | None = None
    request_id: str


class RestoreRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    backup_id: UUID
    traffic_isolated: Annotated[
        Literal[True],
        Field(description="Operator attests that traffic is isolated (OPS-PRP RB07 step 1)"),
    ]
    replay_erasure_ledger: Annotated[
        Literal[True],
        Field(
            description="Always true; erasure tombstones are applied before restored content is readable (ADR-PRP-007)"
        ),
    ]


class OperationTicket(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation_id: UUID
    kind: Literal["backup", "restore"]
    status: Literal["PENDING", "RUNNING", "SUCCEEDED", "FAILED"]
    started_at: AwareDatetime
    finished_at: AwareDatetime | None = None
    audit_event_id: UUID
    request_id: str


class Error(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: ErrorBody
    request_id: str
    safe_to_retry: StrictBool


class QualificationReceipt(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evidence_id: str
    test_ids: Annotated[list[AcceptanceTestId], Field(min_length=1)]
    status: Literal["PASS", "FAIL", "NOT_RUN", "BLOCKED"]
    commit: str
    image_digest: str | None = None
    model_profile_hash: str
    profile_epoch: Annotated[StrictInt, Field(ge=0)]
    hardware: dict[str, Any]
    workload: str | None = None
    sample_count: Annotated[StrictInt | None, Field(ge=0)] = None
    observations: dict[str, Any] | None = None
    result_files: list[str] | None = None
    reviewer: str
    recorded_at: AwareDatetime


class PolicyUpdate(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope: PolicyScope | None = None
    settings: dict[str, Any]
