# Generated by tools/contracts/gen_models.py from contracts/openapi/prp-management.yaml (ADR-PRP-013).
# DO NOT EDIT. Change the YAML, then run: python tools/contracts/gen_models.py
# generated by datamodel-codegen:
#   filename:  prp-management.yaml

from __future__ import annotations

from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, ConfigDict, Field, RootModel, StrictBool, StrictInt

from prp.contracts.base import ContractModel


class ErrorBody(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Literal[
        "INVALID_REQUEST",
        "UNSUPPORTED_PARAMETER",
        "INVALID_KEY",
        "EXPIRED_KEY",
        "SCOPE_DENIED",
        "POLICY_DENIED",
        "POLICY_EXISTS",
        "NOT_FOUND",
        "IDEMPOTENCY_CONFLICT",
        "VERSION_CONFLICT",
        "QUALIFICATION_REQUIRED",
        "STATE_STORE_UNAVAILABLE",
    ]
    type: str
    message: str
    param: str | None = None


class MutationReceipt(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource_id: Annotated[
        str,
        Field(
            description="Stable policy identifier for createPolicy; other operations return their target resource identifier."
        ),
    ]
    version: Annotated[
        str,
        Field(
            description="Opaque resource version to send unchanged as If-Match on the next mutation; on creation this is the initial version."
        ),
    ]
    audit_event_id: UUID
    request_id: str


class ModelAliase(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1)]


class KeyRotationRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    overlap_seconds: Annotated[
        StrictInt,
        Field(
            description="Seconds the old verifier remains valid after rotation; callers may shorten but never exceed the 24-hour default maximum.",
            ge=1,
            le=86400,
        ),
    ] = 86400


class KeyIssuanceReplayReceipt(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key_id: UUID
    key_prefix: Annotated[
        str, Field(description="Non-secret prefix for identification in logs and UI")
    ]
    secret_available: Annotated[
        Literal[False],
        Field(
            description="The plaintext secret is never retained and cannot be recovered after the first response."
        ),
    ]
    version: str
    audit_event_id: UUID


class PoolRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(max_length=64, min_length=1)]
    description: Annotated[str | None, Field(max_length=512)] = None


class NodeRegistration(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    pool_id: UUID
    origin: Annotated[
        str,
        Field(
            description="Allowed worker/adapter endpoint on the private network",
            pattern="^https://",
        ),
    ]
    physical_resource_id: Annotated[
        str,
        Field(
            description="host + GPU UUID, verified host-local identity or CPU pool (ARCH-PRP §5)"
        ),
    ]
    runtime_uid: str
    credential_ref: Annotated[
        str,
        Field(
            description="Reference to the service credential in the secret store; never the credential itself"
        ),
    ]
    desired_profile_id: str


class NodeUpdate(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    origin: Annotated[str | None, Field(pattern="^https://")] = None
    credential_ref: str | None = None
    desired_profile_id: str | None = None
    max_concurrent_invocations: Annotated[StrictInt | None, Field(ge=1)] = None


class AcceptanceTestId(RootModel[str]):
    root: Annotated[str, Field(pattern="^PRP-AT-[0-9]{3}$")]


class StateChangeRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reason: Annotated[str | None, Field(max_length=512)] = None


class ProfileApproval(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["model", "voice"]
    revision: str
    license_receipt_ref: Annotated[
        str,
        Field(
            description="Reference to the recorded license / voice-rights receipt; not the document itself"
        ),
    ]
    approved_until: AwareDatetime | None = None


class PolicySubjectScope(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_type: Literal["principal", "application"]
    subject_id: Annotated[str, Field(max_length=128, min_length=1)]


class WindowBudget(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    limit: Annotated[
        StrictInt,
        Field(
            description="Maximum units admitted in any trailing interval of this duration; events exactly at the interval's lower boundary are excluded.",
            ge=0,
        ),
    ]
    window_seconds: Annotated[
        StrictInt, Field(description="Length of the rolling interval in seconds.", ge=1)
    ]


class RetentionPolicySettings(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    async_payload_terminal_ttl_seconds: Annotated[
        StrictInt,
        Field(
            description="Retention after terminal state, at most 24 hours.",
            ge=0,
            le=86400,
        ),
    ]
    async_payload_max_age_seconds: Annotated[
        StrictInt,
        Field(
            description="Absolute payload age, at most 48 hours from creation.",
            ge=1,
            le=172800,
        ),
    ]
    raw_audio_max_age_seconds: Annotated[
        StrictInt,
        Field(
            description="Absolute raw/orphan audio age, at most 24 hours from upload.",
            ge=1,
            le=86400,
        ),
    ]
    generated_audio_retention_seconds: Annotated[
        StrictInt,
        Field(
            description="Default seven-day retention; authorized deletion may shorten it.",
            ge=1,
        ),
    ]
    job_usage_audit_metadata_retention_days: Annotated[
        StrictInt,
        Field(
            description="Metadata retention in days; policy may shorten the 90-day default.",
            ge=1,
            le=90,
        ),
    ]
    operational_log_retention_days: Annotated[
        StrictInt,
        Field(description="Default 30-day retention for redacted operational logs.", ge=1),
    ]
    share_grant_max_ttl_seconds: Annotated[
        StrictInt,
        Field(
            description="Maximum share-grant TTL; actual expiry must also be no later than artifact expiry.",
            ge=1,
            le=86400,
        ),
    ]


class ExportRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["usage", "audit"]
    from_: Annotated[AwareDatetime, Field(alias="from")]
    to: AwareDatetime
    organization_id: str | None = None


class ExportJob(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    export_id: UUID
    kind: Literal["usage", "audit"]
    status: Literal["PENDING", "READY", "FAILED"]
    redaction: Literal["redacted"]
    artifact_id: UUID | None = None
    expires_at: AwareDatetime | None = None
    request_id: str


class RestoreRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    backup_id: UUID
    traffic_isolated: Annotated[
        Literal[True],
        Field(description="Operator attests that traffic is isolated (OPS-PRP RB07 step 1)"),
    ]
    replay_erasure_ledger: Annotated[
        Literal[True],
        Field(
            description="Always true; erasure tombstones are applied before restored content is readable (ADR-PRP-007)"
        ),
    ]


class OperationTicket(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation_id: UUID
    kind: Literal["backup", "restore"]
    status: Literal["PENDING", "RUNNING", "SUCCEEDED", "FAILED"]
    started_at: AwareDatetime
    finished_at: AwareDatetime | None = None
    audit_event_id: UUID
    request_id: str


class Error(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: ErrorBody
    request_id: str
    safe_to_retry: StrictBool


class AccessGrantRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    organization_id: Annotated[str, Field(max_length=128, min_length=1)]
    subject_type: Literal["organization", "principal", "application"]
    subject_id: Annotated[str, Field(max_length=128, min_length=1)]
    pool_id: UUID
    capabilities: Annotated[
        list[
            Literal[
                "chat:invoke",
                "asr:invoke",
                "tts:invoke",
                "jobs:read",
                "jobs:cancel",
                "artifacts:read",
                "artifacts:delete",
            ]
        ],
        Field(min_length=1),
    ]
    expires_at: AwareDatetime | None


class KeyRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    organization_id: Annotated[str, Field(max_length=128, min_length=1)]
    subject_type: Literal["principal", "application"]
    subject_id: Annotated[str, Field(max_length=128, min_length=1)]
    capabilities: Annotated[
        list[
            Literal[
                "chat:invoke",
                "asr:invoke",
                "tts:invoke",
                "jobs:read",
                "jobs:cancel",
                "artifacts:read",
                "artifacts:delete",
            ]
        ],
        Field(min_length=1),
    ]
    model_aliases: Annotated[
        list[ModelAliase],
        Field(
            description="Public PRP model aliases; vendor model IDs and physical pool IDs are not accepted.",
            min_length=1,
        ),
    ]
    quota_policy_id: Annotated[
        str,
        Field(
            description="Stable resource_id of the quota policy for this key's exact organization and owning subject. All keys for that subject share subject-scope quota counters; the organization policy is also enforced when present.",
            max_length=128,
            min_length=1,
        ),
    ]
    expires_at: AwareDatetime | None
    label: Annotated[str | None, Field(max_length=128)] = None


class KeyIssued(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    key_id: UUID
    secret: Annotated[
        str,
        Field(
            description="Shown once; never retrievable, exportable or restorable afterwards (PRP-FR-005)"
        ),
    ]
    key_prefix: Annotated[
        str, Field(description="Non-secret prefix for identification in logs and UI")
    ]
    secret_available: Literal[True]
    organization_id: Annotated[str, Field(max_length=128, min_length=1)]
    subject_type: Literal["principal", "application"]
    subject_id: Annotated[str, Field(max_length=128, min_length=1)]
    capabilities: Annotated[
        list[
            Literal[
                "chat:invoke",
                "asr:invoke",
                "tts:invoke",
                "jobs:read",
                "jobs:cancel",
                "artifacts:read",
                "artifacts:delete",
            ]
        ],
        Field(min_length=1),
    ]
    model_aliases: Annotated[list[ModelAliase], Field(min_length=1)]
    quota_policy_id: Annotated[
        str,
        Field(
            description="Stable resource_id of this key's exact subject quota policy; all keys for that subject share its counters.",
            max_length=128,
            min_length=1,
        ),
    ]
    expires_at: AwareDatetime | None
    version: str
    audit_event_id: UUID
    request_id: str


class KeyIssuanceResponse(RootModel[KeyIssued | KeyIssuanceReplayReceipt]):
    root: Annotated[
        KeyIssued | KeyIssuanceReplayReceipt,
        Field(
            description="The first successful response contains the plaintext secret; a replay contains only the stable receipt."
        ),
    ]


class QualificationReceipt(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evidence_id: str
    test_ids: Annotated[list[AcceptanceTestId], Field(min_length=1)]
    status: Literal["PASS", "FAIL", "NOT_RUN", "BLOCKED"]
    commit: str
    image_digest: str | None = None
    model_profile_hash: str
    profile_epoch: Annotated[StrictInt, Field(ge=0)]
    hardware: dict[str, Any]
    workload: str | None = None
    sample_count: Annotated[StrictInt | None, Field(ge=0)] = None
    observations: dict[str, Any] | None = None
    result_files: list[str] | None = None
    reviewer: str
    recorded_at: AwareDatetime


class PolicyScope(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    organization_id: Annotated[str, Field(max_length=128, min_length=1)]
    subject: PolicySubjectScope | None = None


class QuotaPolicySettings(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    requests: WindowBudget
    tokens: WindowBudget
    audio_seconds: WindowBudget
    active_jobs: Annotated[
        StrictInt, Field(description="Maximum simultaneously active jobs.", ge=0)
    ]
    queued_jobs: Annotated[
        StrictInt, Field(description="Maximum simultaneously queued jobs.", ge=0)
    ]
    storage_bytes: Annotated[
        StrictInt,
        Field(description="Maximum retained storage allowance in bytes.", ge=0),
    ]


class PolicyWrite(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scope: PolicyScope
    settings: QuotaPolicySettings | RetentionPolicySettings


class PolicyResource(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource_id: Annotated[str, Field(max_length=128, min_length=1)]
    policy_kind: Literal["quota", "retention"]
    scope: PolicyScope
    settings: QuotaPolicySettings | RetentionPolicySettings
    version: Annotated[str, Field(max_length=128, min_length=1)]
