# Generated by tools/contracts/gen_models.py from contracts/openapi/prp-worker.yaml (ADR-PRP-013).
# DO NOT EDIT. Change the YAML, then run: python tools/contracts/gen_models.py
# generated by datamodel-codegen:
#   filename:  prp-worker.yaml

from __future__ import annotations

from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import (
    AwareDatetime,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
)

from prp_voice.contract.base import ContractModel


class ErrorBody(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Literal[
        "INVALID_REQUEST",
        "UNSUPPORTED_PARAMETER",
        "PAYLOAD_TOO_LARGE",
        "EPOCH_MISMATCH",
        "FENCE_REJECTED",
        "NOT_FOUND",
        "UNSUPPORTED",
        "CONTEXT_LIMIT",
        "NO_SPEECH",
        "AUDIO_UNINTELLIGIBLE",
        "RUNTIME_UNAVAILABLE",
        "DEADLINE_EXCEEDED",
    ]
    type: str
    message: Annotated[
        str,
        Field(description="Sanitized; never an upstream body or stack trace (Coding-Standards §5)"),
    ]
    param: str | None = None


class RuntimeIdentity(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    manager_uid: Annotated[
        str | None,
        Field(
            description="Lifecycle manager identity when a runtime manager (candidate A) is in use; null for independently supervised services (candidate B)"
        ),
    ] = None
    runtime_uid: str
    physical_resource_id: Annotated[
        str,
        Field(
            description="host + GPU UUID, verified host-local identity, or CPU pool identifier (ARCH-PRP §5)"
        ),
    ]
    profile_hash: str
    profile_epoch: Annotated[StrictInt, Field(ge=0)]
    engine: Annotated[
        str,
        Field(
            description="Engine name and version as reported by the adapter; informational, not a qualification claim"
        ),
    ]
    adapter_version: str
    evidence_revision: Annotated[
        str | None,
        Field(
            description="Revision of the qualification evidence this identity was last bound to; empty when unqualified"
        ),
    ] = None


class Limits(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_context_tokens: Annotated[StrictInt | None, Field(ge=1)] = None
    max_audio_seconds: Annotated[StrictFloat | None, Field(gt=0.0)] = None
    max_input_bytes: Annotated[StrictInt | None, Field(ge=1)] = None
    max_tts_codepoints: Annotated[StrictInt | None, Field(ge=1)] = None
    max_concurrent_invocations: Annotated[StrictInt | None, Field(ge=1)] = None


class Capability(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model: Annotated[
        str,
        Field(
            description="Served profile identifier (not the public alias; the control plane owns alias -> profile mapping)"
        ),
    ]
    profile_revision: str
    capabilities: list[Literal["chat", "asr", "tts", "tool_calls"]]
    languages: list[str] | None = None
    formats: list[str] | None = None
    limits: Limits | None = None


class CancellationSupport(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    supported: StrictBool
    termination_evidence: Annotated[
        StrictBool,
        Field(description="true when getExecutionEvidence can distinguish FINISHED from UNKNOWN"),
    ]


class Readiness(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    state: Annotated[
        Literal["READY", "NOT_READY", "UNKNOWN"],
        Field(
            description="NOT_READY covers loading/draining (added in this draft for review at WP03; API-PRP §7 lists READY/UNKNOWN). UNKNOWN means the adapter cannot observe the engine."
        ),
    ]
    profile_epoch: Annotated[StrictInt, Field(description="Actual epoch of the runtime", ge=0)]
    observed_at: AwareDatetime
    limits: Limits | None = None


class FunctionCall(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    arguments: str


class ToolFunction(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    description: str | None = None
    parameters: dict[str, Any] | None = None


class FunctionName(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str


class AsrPayload(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["asr"]
    profile_id: str
    artifact_grant_url: Annotated[
        str,
        Field(
            description="Time-bound, revocable read grant minted by PRP for this attempt only. The worker never receives a client key or storage credential.",
            pattern="^https://",
        ),
    ]
    mime_type: str
    duration_seconds: Annotated[StrictFloat, Field(gt=0.0)]
    language: Literal["th", "en", "auto"] = "auto"


class TtsPayload(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["tts"]
    profile_id: str
    input: Annotated[str, Field(max_length=800, min_length=1)]
    voice: Annotated[
        str,
        Field(
            description="Approved preset identifier; reference audio/text is server-side preset state, never part of the payload (API-PRP §4)"
        ),
    ]
    response_format: Literal["wav", "mp3"]
    speed: Annotated[StrictFloat, Field(ge=0.5, le=2.0)] = 1


class Usage(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    prompt_tokens: Annotated[StrictInt | None, Field(ge=0)] = None
    completion_tokens: Annotated[StrictInt | None, Field(ge=0)] = None
    total_tokens: Annotated[StrictInt | None, Field(ge=0)] = None
    audio_seconds: Annotated[StrictFloat | None, Field(ge=0.0)] = None


class Segment(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start: Annotated[StrictFloat, Field(ge=0.0)]
    end: Annotated[StrictFloat, Field(ge=0.0)]
    text: str


class Transcript(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str
    language: str
    duration_seconds: Annotated[StrictFloat, Field(ge=0.0)]
    segments: list[Segment] | None = None


class EvidenceDetail(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    process_alive: StrictBool | None = None
    terminated_at: AwareDatetime | None = None
    exit_reason: str | None = None


class CancelRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    fence_token: Annotated[str, Field(max_length=128, min_length=16)]


class CancelResult(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    attempt_id: UUID
    disposition: Literal["ACK", "UNSUPPORTED", "ALREADY_FINISHED"]
    observed_at: AwareDatetime


class Error(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: ErrorBody
    request_id: str
    safe_to_retry: Annotated[
        StrictBool,
        Field(description="false whenever the attempt may have been dispatched or started"),
    ]


class Describe(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    identity: RuntimeIdentity
    capabilities: Annotated[list[Capability], Field(min_length=1)]
    cancellation: CancellationSupport
    observed_at: AwareDatetime


class ToolCall(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    type: Literal["function"]
    function: FunctionCall


class Message(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Literal["system", "user", "assistant", "tool"]
    content: str | None
    tool_call_id: str | None = None
    tool_calls: list[ToolCall] | None = None


class Tool(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["function"]
    function: ToolFunction


class NamedToolChoice(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["function"]
    function: FunctionName


class ChatChoice(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    index: Literal[0]
    message: Message
    finish_reason: Literal["stop", "length", "tool_calls"]


class ChatDelta(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Literal["assistant"] | None = None
    content: str | None = None
    tool_calls: list[ToolCall] | None = None


class ChatResult(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    choices: Annotated[list[ChatChoice], Field(max_length=1, min_length=1)]


class ExecutionEvidence(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    attempt_id: UUID
    runtime_epoch: Annotated[
        StrictInt, Field(description="Actual runtime epoch at observation", ge=0)
    ]
    evidence: Literal["RUNNING", "FINISHED", "UNKNOWN"]
    detail: EvidenceDetail | None = None
    observed_at: AwareDatetime


class ChatPayload(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["chat"]
    profile_id: str
    messages: Annotated[list[Message], Field(min_length=1)]
    stream: StrictBool = False
    temperature: Annotated[StrictFloat | None, Field(ge=0.0, le=2.0)] = None
    top_p: Annotated[StrictFloat | None, Field(gt=0.0, le=1.0)] = None
    max_tokens: Annotated[
        StrictInt,
        Field(
            description="Required here (bounded payload); the worker must not exceed it",
            ge=1,
        ),
    ]
    tools: list[Tool] | None = None
    tool_choice: Literal["auto", "none", "required"] | NamedToolChoice | None = None


class InvocationRequest(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    invocation_id: UUID
    attempt_id: UUID
    profile_epoch: Annotated[
        StrictInt,
        Field(
            description="Epoch the reservation was made against; the worker rejects a mismatch with 409 EPOCH_MISMATCH",
            ge=0,
        ),
    ]
    fence_token: Annotated[
        str,
        Field(
            description="Content fence for this attempt; required again on cancel",
            max_length=128,
            min_length=16,
        ),
    ]
    deadline_at: Annotated[
        AwareDatetime,
        Field(
            description="Absolute deadline. The worker stops emitting at this instant; PRP treats the outcome as UNKNOWN until evidence"
        ),
    ]
    payload: Annotated[ChatPayload | AsrPayload | TtsPayload, Field(discriminator="kind")]


class ChatChunkChoice(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    index: Literal[0]
    delta: ChatDelta
    finish_reason: Literal["stop", "length", "tool_calls"] | None


class InvocationResult(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    invocation_id: UUID
    attempt_id: UUID
    runtime_uid: str
    physical_resource_id: str
    profile_epoch: Annotated[StrictInt, Field(ge=0)]
    kind: Annotated[
        Literal["chat", "asr"],
        Field(description="tts results are returned as binary content with metadata headers"),
    ]
    result: ChatResult | Transcript
    usage: Usage | None = None
    usage_provenance: Literal["actual", "estimated", "unavailable"]
    execution_ms: Annotated[
        StrictInt | None,
        Field(description="Measured wall time on the runtime for this attempt", ge=0),
    ] = None
    observed_at: AwareDatetime


class ChatChunk(ContractModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    choices: list[ChatChunkChoice]
    usage: Usage | None = None
