#!/usr/bin/env python3
"""Generate Pydantic contract models from contracts/openapi/*.yaml (ADR-PRP-013).

Table-driven: contract -> project -> output module -> base class. Runs the pinned
datamodel-code-generator with the flags fixed by ADR-PRP-013 rule 3, then the target project's own
``ruff check --fix --select I`` and ``ruff format`` (through ``uv run --locked``) so the committed
output is canonical and byte-stable. Generated modules are derived files: never edit them by hand.

Usage:
  python tools/contracts/gen_models.py           # (re)write every generated module
  python tools/contracts/gen_models.py --check   # exit 1 when any committed module is stale

Requires ``pip install -r tools/contracts/requirements.txt`` (pinned generator) and ``uv`` with every
target project synced (``uv sync --locked --group dev``).
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OPENAPI = ROOT / "contracts" / "openapi"


@dataclass(frozen=True)
class Target:
    contract: str
    project: str
    output: str
    base_class: str


# One base class per project (ADR-PRP-013 rule 4). Generated modules live in a package below the
# api | adapters layer so both may import them without importing each other (SDD-PRP-REPO 6.3).
TARGETS: tuple[Target, ...] = (
    Target("prp-client", "apps/control-api", "src/prp/contracts/client_v1.py", "prp.contracts.base.ContractModel"),
    Target("prp-worker", "apps/control-api", "src/prp/contracts/worker_v1.py", "prp.contracts.base.ContractModel"),
    Target("prp-management", "apps/control-api", "src/prp/contracts/management_v1.py", "prp.contracts.base.ContractModel"),
    Target("prp-worker", "workers/voice", "src/prp_voice/contract/generated.py", "prp_voice.contract.base.ContractModel"),
)

# Fixed by ADR-PRP-013 rule 3. Changing a flag is an ADR amendment, not a tooling tweak.
FLAGS: tuple[str, ...] = (
    "--input-file-type", "openapi",
    "--output-model-type", "pydantic_v2.BaseModel",
    "--target-python-version", "3.12",
    "--use-annotated",
    "--field-constraints",
    "--strict-nullable",
    "--strict-types", "int", "float", "bool",
    "--use-union-operator",
    "--use-standard-collections",
    "--enum-field-as-literal", "all",
    "--use-double-quotes",
    "--disable-timestamp",
    "--collapse-root-models",
)

HEADER = (
    "# Generated by tools/contracts/gen_models.py from contracts/openapi/{contract}.yaml (ADR-PRP-013).\n"
    "# DO NOT EDIT. Change the YAML, then run: python tools/contracts/gen_models.py\n"
)


def run(command: list[str], *, cwd: Path) -> None:
    result = subprocess.run(command, cwd=cwd, capture_output=True, text=True, encoding="utf-8", errors="replace")
    if result.returncode != 0:
        sys.stderr.write(result.stdout[-3000:] + result.stderr[-3000:])
        raise SystemExit(f"command failed ({result.returncode}): {' '.join(command[:4])} ...")


def generate(target: Target) -> str:
    project = ROOT / target.project
    output = project / target.output
    output.parent.mkdir(parents=True, exist_ok=True)
    temp = output.with_name(f"_{output.stem}_gen_tmp.py")
    try:
        run(
            [
                sys.executable, "-m", "datamodel_code_generator",
                "--input", str(OPENAPI / f"{target.contract}.yaml"),
                "--output", str(temp),
                "--base-class", target.base_class,
                *FLAGS,
            ],
            cwd=ROOT,
        )
        temp.write_text(HEADER.format(contract=target.contract) + temp.read_text(encoding="utf-8"), encoding="utf-8", newline="\n")
        run(["uv", "run", "--locked", "ruff", "check", "--fix", "--select", "I", "-q", str(temp)], cwd=project)
        run(["uv", "run", "--locked", "ruff", "format", "-q", str(temp)], cwd=project)
        return temp.read_text(encoding="utf-8")
    finally:
        temp.unlink(missing_ok=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify committed modules instead of writing them")
    args = parser.parse_args()

    stale: list[str] = []
    for target in TARGETS:
        output = ROOT / target.project / target.output
        rel = output.relative_to(ROOT).as_posix()
        rendered = generate(target)
        current = output.read_text(encoding="utf-8") if output.exists() else None
        if current == rendered:
            print(f"unchanged {rel}")
            continue
        if args.check:
            stale.append(rel)
            continue
        output.write_text(rendered, encoding="utf-8", newline="\n")
        print(f"wrote     {rel}")

    if args.check and stale:
        print("STALE generated module(s); run: python tools/contracts/gen_models.py", file=sys.stderr)
        for rel in stale:
            print(f"  {rel}", file=sys.stderr)
        return 1
    if args.check:
        print(f"OK: {len(TARGETS)} generated module(s) match their contracts")
    return 0


if __name__ == "__main__":
    sys.exit(main())
